name: SendYourFiles Builder
on:
    push:
        branches: [all]
    pull_request:
        branches: [all]

env:
    pythonVersion: 3.13.11

jobs:
    build:
        name: Build for ${{ matrix.os-name }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                  - os: ubuntu-latest
                    os-name: Linux Ubuntu
                    artifact-path: dist/SendYourFiles-Linux
                    artifact-name: SendYourFiles-Linux
                  - os: windows-latest
                    os-name: Windows
                    artifact-path: dist/SendYourFiles-Windows.exe
                    artifact-name: SendYourFiles-Windows
                  - os: macos-latest
                    os-name: MacOS
                    artifact-path: dist/SendYourFiles-MacOS
                    artifact-name: SendYourFiles-MacOS
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python ${{ env.pythonVersion }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ env.pythonVersion }}
            
            - name: Install Python dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Compile with PyInstaller
              run: pyinstaller build.spec

            - name: Rename Build (Windows)
              if: runner.os == 'Windows'
              run: move dist\SendYourFiles.exe ${{ matrix.artifact-path }}

            - name: Rename Build (Linux/macOS)
              if: runner.os != 'Windows'
              run: mv dist/SendYourFiles ${{ matrix.artifact-path }}

            - name: Upload Build Artifact
              uses: actions/upload-artifact@v4
              with:
                name: ${{ matrix.artifact-name }}
                path: ${{ matrix.artifact-path }}